"""add email and fix teach_lesson as string

Revision ID: 0d602892359a
Revises: d4f0c771bf6c
Create Date: 2026-02-13 14:37:20.952264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d602892359a'
down_revision: Union[str, Sequence[str], None] = 'd4f0c771bf6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('describe_of_score', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'describe_of_score')
    # ### end Alembic commands ###
