"""Create teacher, student table, user

Revision ID: 11e91026bca4
Revises: cbfe5ba3b5db
Create Date: 2026-02-06 10:08:36.696381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11e91026bca4'
down_revision: Union[str, Sequence[str], None] = 'cbfe5ba3b5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('hash_password', sa.String(), nullable=True),
    sa.Column('education_level', sa.Enum('School', 'College', 'University', name='educationlevel'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_education_level'), 'users', ['education_level'], unique=False)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_middle_name'), 'users', ['middle_name'], unique=False)
    op.drop_index(op.f('ix_student_current_education_level'), table_name='student')
    op.drop_index(op.f('ix_student_first_name'), table_name='student')
    op.drop_index(op.f('ix_student_id'), table_name='student')
    op.drop_index(op.f('ix_student_last_name'), table_name='student')
    op.drop_index(op.f('ix_student_middle_name'), table_name='student')
    op.create_foreign_key(None, 'student', 'users', ['id'], ['id'])
    op.drop_column('student', 'date_of_birth')
    op.drop_column('student', 'current_education_level')
    op.drop_column('student', 'first_name')
    op.drop_column('student', 'last_name')
    op.drop_column('student', 'middle_name')
    op.drop_column('student', 'hash_password')
    op.drop_index(op.f('ix_teacher_education_level'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_first_name'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_id'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_last_name'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_middle_name'), table_name='teacher')
    op.create_foreign_key(None, 'teacher', 'users', ['id'], ['id'])
    op.drop_column('teacher', 'education_level')
    op.drop_column('teacher', 'date_of_birth')
    op.drop_column('teacher', 'first_name')
    op.drop_column('teacher', 'last_name')
    op.drop_column('teacher', 'middle_name')
    op.drop_column('teacher', 'hash_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('education_level', postgresql.ENUM('School', 'College', 'University', name='educationlevel'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.create_index(op.f('ix_teacher_middle_name'), 'teacher', ['middle_name'], unique=False)
    op.create_index(op.f('ix_teacher_last_name'), 'teacher', ['last_name'], unique=False)
    op.create_index(op.f('ix_teacher_id'), 'teacher', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_first_name'), 'teacher', ['first_name'], unique=False)
    op.create_index(op.f('ix_teacher_education_level'), 'teacher', ['education_level'], unique=False)
    op.add_column('student', sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('current_education_level', postgresql.ENUM('School', 'College', 'University', name='educationlevel'), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_index(op.f('ix_student_middle_name'), 'student', ['middle_name'], unique=False)
    op.create_index(op.f('ix_student_last_name'), 'student', ['last_name'], unique=False)
    op.create_index(op.f('ix_student_id'), 'student', ['id'], unique=False)
    op.create_index(op.f('ix_student_first_name'), 'student', ['first_name'], unique=False)
    op.create_index(op.f('ix_student_current_education_level'), 'student', ['current_education_level'], unique=False)
    op.drop_index(op.f('ix_users_middle_name'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_education_level'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
