"""add email and fix teach_lesson as string

Revision ID: 92c83b68e18c
Revises: 11e91026bca4
Create Date: 2026-02-13 13:20:31.855817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92c83b68e18c'
down_revision: Union[str, Sequence[str], None] = '11e91026bca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'teach_lesson',
               existing_type=postgresql.ENUM('physics', 'mathematics', 'english', 'russian', 'geography', 'literature', name='lessons'),
               type_=sa.Enum('physics', 'mathematics', 'english', 'russian', 'geography', 'literature', name='lesson', native_enum=False),
               existing_nullable=True)
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'hash_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'education_level',
               existing_type=postgresql.ENUM('School', 'College', 'University', name='educationlevel'),
               nullable=False)
    op.drop_index(op.f('ix_users_education_level'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_middle_name'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_middle_name'), 'users', ['middle_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_education_level'), 'users', ['education_level'], unique=False)
    op.alter_column('users', 'education_level',
               existing_type=postgresql.ENUM('School', 'College', 'University', name='educationlevel'),
               nullable=True)
    op.alter_column('users', 'hash_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'email')
    op.alter_column('teacher', 'teach_lesson',
               existing_type=sa.Enum('physics', 'mathematics', 'english', 'russian', 'geography', 'literature', name='lesson', native_enum=False),
               type_=postgresql.ENUM('physics', 'mathematics', 'english', 'russian', 'geography', 'literature', name='lessons'),
               existing_nullable=True)
    # ### end Alembic commands ###
