"""Initial tables

Revision ID: cbfe5ba3b5db
Revises: 
Create Date: 2026-02-05 14:35:32.665395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfe5ba3b5db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('hash_password', sa.String(), nullable=True),
    sa.Column('current_education_level', sa.Enum('School', 'College', 'University', name='educationlevel'), nullable=True),
    sa.Column('desired_score', sa.Integer(), nullable=True),
    sa.Column('education_class', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_current_education_level'), 'student', ['current_education_level'], unique=False)
    op.create_index(op.f('ix_student_first_name'), 'student', ['first_name'], unique=False)
    op.create_index(op.f('ix_student_id'), 'student', ['id'], unique=False)
    op.create_index(op.f('ix_student_last_name'), 'student', ['last_name'], unique=False)
    op.create_index(op.f('ix_student_middle_name'), 'student', ['middle_name'], unique=False)
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('teach_lesson', sa.Enum('physics', 'mathematics', 'english', 'russian', 'geography', 'literature', name='lessons'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('hash_password', sa.String(), nullable=True),
    sa.Column('teacher_experience', sa.Integer(), nullable=True),
    sa.Column('experience_description', sa.String(), nullable=True),
    sa.Column('education_level', sa.Enum('School', 'College', 'University', name='educationlevel'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_education_level'), 'teacher', ['education_level'], unique=False)
    op.create_index(op.f('ix_teacher_first_name'), 'teacher', ['first_name'], unique=False)
    op.create_index(op.f('ix_teacher_id'), 'teacher', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_last_name'), 'teacher', ['last_name'], unique=False)
    op.create_index(op.f('ix_teacher_middle_name'), 'teacher', ['middle_name'], unique=False)
    op.create_index(op.f('ix_teacher_teach_lesson'), 'teacher', ['teach_lesson'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_teach_lesson'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_middle_name'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_last_name'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_id'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_first_name'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_education_level'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_student_middle_name'), table_name='student')
    op.drop_index(op.f('ix_student_last_name'), table_name='student')
    op.drop_index(op.f('ix_student_id'), table_name='student')
    op.drop_index(op.f('ix_student_first_name'), table_name='student')
    op.drop_index(op.f('ix_student_current_education_level'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
